name: Python CI Demo

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Get your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      # 3. Install pytest
      - name: Install dependencies
        run: pip install pytest

      # 4. Run test
      - name: Run tests
        run: pytest